import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const assetsDir = path.join(__dirname, '..', 'public', 'assets');
if (!fs.existsSync(assetsDir)) {
  fs.mkdirSync(assetsDir, { recursive: true });
}

const colors = {
  '.': 'transparent',
  'G': '#15803d', // Stem / dark green
  'L': '#22c55e', // Leaf / light green
  'P': '#a855f7', // Purple flower
  'D': '#6b21a8', // Purple shadow
  'W': '#ffffff', // White flower
  'S': '#94a3b8', // White shadow
  'Y': '#eab308', // Yellow pod
  'O': '#a16207', // Yellow pod shadow
  'H': '#4ade80', // Green pod
  'K': '#166534', // Green pod shadow
  'R': '#ef4444', // Red center (optional)
  'A': '#facc15'  // Yellow/gold accent
};

function renderMatrixToSvg(matrix) {
  let rects = '';
  const rows = matrix.trim().split('\n');
  const height = rows.length;
  const width = rows[0].trim().split('').length;
  
  for (let y = 0; y < height; y++) {
    const cols = rows[y].trim().split('');
    for (let x = 0; x < width; x++) {
      const char = cols[x];
      const color = colors[char];
      if (color && color !== 'transparent') {
        rects += `  <rect x="${x}" y="${y}" width="1" height="1" fill="${color}" />\n`;
      }
    }
  }
  
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${width} ${height}" width="100%" height="100%" shape-rendering="crispEdges">
${rects}</svg>`;
}

// 24x24 Pixel Art templates
// Plant A: Purple flower, Green pod
const plantAMatrix = `
........................
.........PPPP...........
........PPPPPP..........
.......PPDDPPPP.........
.......PDDDDPPP.........
........PDDPP...........
.........GG.............
.......LLGGLL...........
......LLLLGGLL..........
.....LLLLGGLLLL.........
.....LL.GG..LL..........
........GG.HHHH.........
........GGKHHHH.........
......LLGGKKK...........
.....LLLLGG.............
....LLLLGG.HH...........
....LL.GG..HH...........
.......GG...............
.......GG...............
.......GG...............
.......GG...............
........................
........................
........................
`;

// Plant B: White flower, Yellow pod
const plantBMatrix = `
........................
.........WWWW...........
........WWWWWW..........
.......WWSSWWWW.........
.......WSSSSWWW.........
........WWSSW...........
.........GG.............
.......LLGGLL...........
......LLLLGGLL..........
.....LLLLGGLLLL.........
.....LL.GG..LL..........
........GG.YYYY.........
........GGYYYYY.........
......LLGGOOO...........
.....LLLLGG.............
....LLLLGG.YY...........
....LL.GG..YY...........
.......GG...............
.......GG...............
.......GG...............
.......GG...............
........................
........................
........................
`;

// Plant C: Purple flower, Green pod (shorter stem, distinct layout)
const plantCMatrix = plantAMatrix; // Let's keep them distinct by changing flower/pod combo
// Plant D: White flower, Green pod
const plantDMatrix = `
........................
.........WWWW...........
........WWWWWW..........
.......WWSSWWWW.........
.......WSSSSWWW.........
........WWSSW...........
.........GG.............
.......LLGGLL...........
......LLLLGGLL..........
.....LLLLGGLLLL.........
.....LL.GG..LL..........
........GG.HHHH.........
........GGKHHHH.........
......LLGGKKK...........
.....LLLLGG.............
....LLLLGG.HH...........
....LL.GG..HH...........
.......GG...............
.......GG...............
.......GG...............
.......GG...............
........................
........................
........................
`;

// Plant E: Purple flower, Yellow pod
const plantEMatrix = `
........................
.........PPPP...........
........PPPPPP..........
.......PPDDPPPP.........
.......PDDDDPPP.........
........PDDPP...........
.........GG.............
.......LLGGLL...........
......LLLLGGLL..........
.....LLLLGGLLLL.........
.....LL.GG..LL..........
........GG.YYYY.........
........GGYYYYY.........
......LLGGOOO...........
.....LLLLGG.............
....LLLLGG.YY...........
....LL.GG..YY...........
.......GG...............
.......GG...............
.......GG...............
.......GG...............
........................
........................
........................
`;

// Plant F: White flower, Green pod
const plantFMatrix = plantDMatrix;

const plantMatrices = {
  'pixel_plant_a.svg': plantAMatrix,
  'pixel_plant_b.svg': plantBMatrix,
  'pixel_plant_c.svg': plantCMatrix,
  'pixel_plant_d.svg': plantDMatrix,
  'pixel_plant_e.svg': plantEMatrix,
  'pixel_plant_f.svg': plantFMatrix
};

for (const [filename, matrix] of Object.entries(plantMatrices)) {
  const content = renderMatrixToSvg(matrix);
  fs.writeFileSync(path.join(assetsDir, filename), content, 'utf8');
  console.log(`Created new pixel plant: ${filename}`);
}
